[F] Handle conflicting files
repositive/rps pull request #6
Opened 2017-06-30 11:23 UTC by hectorhuertas

2017-07-03 08:44 UTC, Istar-Eldritch requested changes

2017-07-03 08:44 UTC, Istar-Eldritch commented on src/main/gen/index.ts
> +      }
What is the info? What would be the purpose of it?

2017-07-03 08:44 UTC, Istar-Eldritch commented on src/main/gen/templates.ts
> +          File: "${tpl}" already exists, do you want to ovewrite it?`);
There is a typo here. It should be `overwrite`.

2017-07-03 09:08 UTC, hectorhuertas commented on src/main/gen/index.ts
> +      }
Let the user know what task is going to run, like "generating templates"

2017-07-03 09:10 UTC, hectorhuertas commented on src/main/gen/templates.ts
> +          File: "${tpl}" already exists, do you want to ovewrite it?`);
Thats how the cool kids write it today, xD

2017-07-05 12:20 UTC, hectorhuertas commented
@Istar-Eldritch i think I addressed your changes. Can you review it?

2017-07-05 12:26 UTC, Istar-Eldritch approved these changes
LGTM

2017-07-05 12:26 UTC, merged